name: chat_app_g8
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  cupertino_icons: ^1.0.2

  auto_route: ^7.8.4

  shared_preferences: ^2.2.2

  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  firebase_database: ^10.3.8
  firebase_storage: ^11.5.6
  cloud_firestore: ^4.13.6

  mask_text_input_formatter: ^2.7.0

  pinput: ^3.0.1

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  firebase_app_check: ^0.2.1+8

  cached_network_image: ^3.3.0
  image_picker: ^1.0.5
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
  freezed: ^2.4.6

flutter:
  uses-material-design: true


